version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/learnstyle_ai
    depends_on:
      - db
    volumes:
      - ./instance:/app/instance
      - ./ml_models:/app/ml_models
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=learnstyle_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
